[build]
  # base = "/opt/build/repo/src"
  publish = "out"
  command = "yarn install && yarn build"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[plugins]
package = "@netlify/plugin-nextjs"