import Head from 'next/head';

export default function HeadMeta ({ props }: { props: any }) {
  return (
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
